---
- hosts: all
  become: true
  become_method: sudo

  vars:
    docker_users:
    - vagrant

  pre_tasks:
  - name: Include custom_vars.yml
    include_vars:
      file: custom_vars.yml

  roles:
  - andrelohmann.root_colored_prompt
  - andrelohmann.docker
  - andrelohmann.gitlab_docker_runner

...
